#!/usr/bin/env node
/**
 * new-app — scaffold a new app for the studio site
 *
 * Usage
 * ─────
 *   npm run new-app -- <slug> ["App Name"]
 *
 * Examples
 * ────────
 *   npm run new-app -- focus-timer
 *   npm run new-app -- focus-timer "Focus Timer"
 *
 * What it does
 * ────────────
 *   1. Creates  data/apps/<slug>.ts   (the new app's data file)
 *   2. Patches  data/apps/index.ts    (adds the import + registers the app)
 *
 * After running, search for TODO: in the generated file to see
 * what to fill in before launch.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

/* ─── Helpers ─────────────────────────────────────────────────── */

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, "..");

function rel(p) { return resolve(root, p); }

/** "my-app-slug" → "myAppSlug" */
function toCamelCase(slug) {
  return slug.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/** "my-app-slug" → "My App Slug" */
function toTitleCase(slug) {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function exit(msg) {
  console.error(`\n✗  ${msg}\n`);
  process.exit(1);
}

/* ─── Args ────────────────────────────────────────────────────── */

const [, , rawSlug, rawName] = process.argv;

if (!rawSlug) {
  console.log(`
Usage:  npm run new-app -- <slug> ["App Name"]

  slug      kebab-case identifier used in URLs  e.g. focus-timer
  App Name  display name (optional)             e.g. "Focus Timer"
            Defaults to title-cased slug.
`);
  process.exit(0);
}

// Validate slug
if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(rawSlug)) {
  exit(
    `"${rawSlug}" is not a valid slug.\n` +
    `   Slugs must be lowercase letters, numbers, and hyphens.\n` +
    `   Example: focus-timer`
  );
}

const slug    = rawSlug;
const name    = rawName ?? toTitleCase(slug);
const varName = toCamelCase(slug);

/* ─── Paths ───────────────────────────────────────────────────── */

const appFile      = rel(`data/apps/${slug}.ts`);
const registryFile = rel("data/apps/index.ts");

if (existsSync(appFile)) {
  exit(`data/apps/${slug}.ts already exists. Choose a different slug.`);
}

/* ─── Generate app file ───────────────────────────────────────── */

const appFileContent = `\
import { createApp } from "./defaults";

/**
 * ${name}
 *
 * Generated by: npm run new-app -- ${slug} "${name}"
 *
 * Quick-start checklist
 * ─────────────────────
 * TODO: Set status to "beta" or "live" when the app ships.
 * TODO: Replace tagline and summary with real copy.
 * TODO: Add your brand accent color.
 * TODO: Fill in features[], screenshots[], audience[], faq[].
 * TODO: Add real App Store / Play Store links before launch.
 * TODO: Have the auto-generated privacy + terms reviewed by legal counsel.
 *
 * See data/apps/unfumbled.ts for a fully-featured example.
 */
export const ${varName} = createApp({
  slug:      "${slug}",
  name:      "${name}",
  tagline:   "One-line tagline for cards and previews.",    // TODO
  summary:   "A short description shown on cards and in SEO metadata.", // TODO
  status:    "coming-soon",   // "live" | "beta" | "coming-soon"
  platforms: ["ios", "android"],
  accent:    "#0B5FFF",       // TODO: brand color
  category:  "Productivity",  // TODO

  // ── Uncomment and fill in as the app develops ─────────────────────────

  // headline:    "Strong hero headline that leads with the benefit.",
  // subheadline: "One or two sentences expanding on the headline.",
  // whatItDoes:  "A paragraph explaining the core idea. Not marketing copy.",

  // highlights: [
  //   { label: "Free to try" },
  //   { label: "No account required" },
  //   { label: "iOS & Android" },
  //   { label: "Private by default" },
  // ],

  // features: [
  //   { title: "Feature name", description: "What it does and why it matters." },
  //   { title: "Feature name", description: "What it does and why it matters." },
  //   { title: "Feature name", description: "What it does and why it matters." },
  // ],

  // screenshots: [
  //   { src: "/screenshots/${slug}-1.png", alt: "Screen description", caption: "Caption", subcaption: "One-liner." },
  //   { src: "/screenshots/${slug}-2.png", alt: "Screen description", caption: "Caption", subcaption: "One-liner." },
  //   { src: "/screenshots/${slug}-3.png", alt: "Screen description", caption: "Caption", subcaption: "One-liner." },
  // ],

  // audience: [
  //   { title: "Persona name", description: "Why this app is right for them." },
  //   { title: "Persona name", description: "Why this app is right for them." },
  // ],

  // faq: [
  //   { q: "Is it free?",          a: "Yes. Core features are always free." },
  //   { q: "Do I need an account?", a: "No. Open and start immediately." },
  // ],

  // links: [
  //   { label: "Download on the App Store", href: "https://apps.apple.com/...", kind: "store", note: "Free on iOS" },
  //   { label: "Get it on Google Play",     href: "https://play.google.com/...", kind: "store", note: "Free on Android" },
  // ],

  // ctaTitle: "Your headline for the bottom CTA block.",
  // ctaBody:  "Supporting sentence. Keep it short.",

  // featured: true,   // set to make this the homepage flagship

  // ── Override auto-generated legal docs if needed ──────────────────────
  // privacy: { lastUpdated: "...", sections: [...] },
  // terms:   { lastUpdated: "...", sections: [...] },
});
`;

/* ─── Patch registry (index.ts) ───────────────────────────────── */

const registryContent = readFileSync(registryFile, "utf8");

// 1. Add import line after the last existing import statement.
//    Matches lines like:  import { foo } from "./foo";
const lastImportMatch = [...registryContent.matchAll(/^import .+ from ".+";$/gm)].pop();

if (!lastImportMatch) {
  exit("Could not locate an import statement in data/apps/index.ts. Patch it manually.");
}

const insertImportAt = lastImportMatch.index + lastImportMatch[0].length;
const newImportLine  = `\nimport { ${varName} } from "./${slug}";`;

let patched = registryContent.slice(0, insertImportAt) + newImportLine + registryContent.slice(insertImportAt);

// 2. Add the variable to the apps array.
//    Matches:  export const apps: App[] = [something];
//    or multi-line variants
const arrayMatch = patched.match(/(export const apps: App\[\] = \[)([^\]]*?)(\];)/s);

if (!arrayMatch) {
  exit("Could not locate `export const apps: App[]` in data/apps/index.ts. Add it manually.");
}

const before   = arrayMatch[1];
const existing = arrayMatch[2].trimEnd();
const after    = arrayMatch[3];

// Append the new app to the array, preserving existing content.
const comma     = existing.trim().length > 0 ? "," : "";
const newEntry  = `${existing}${comma} ${varName}`;
patched = patched.replace(arrayMatch[0], `${before}${newEntry}${after}`);

/* ─── Write files ─────────────────────────────────────────────── */

writeFileSync(appFile,      appFileContent, "utf8");
writeFileSync(registryFile, patched,        "utf8");

/* ─── Success output ──────────────────────────────────────────── */

console.log(`
✓  Created   data/apps/${slug}.ts
✓  Registered in data/apps/index.ts

Your new app is live at:
   /apps/${slug}
   /apps/${slug}/privacy
   /apps/${slug}/terms

Next steps:
  1. Open data/apps/${slug}.ts
  2. Follow the TODO comments to fill in copy
  3. Run \`npm run dev\` and visit /apps/${slug} to preview
  4. Swap status to "beta" or "live" when ready to ship
  5. Replace the auto-generated Privacy Policy and Terms
     with reviewed legal text before publishing to the App Store.

Tip: See data/apps/unfumbled.ts for a fully-featured example.
`);
